on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: "Build & Release edit"
jobs:
  build: 
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: 3.19.0
     - run: flutter pub get
     - run: flutter test
     - run: flutter build apk
     - uses: ncipollo/release-action@v1
       with:
        artifacts: "build/app/outputs/apk/debug/*"
        tag: v1.0.${{ github.run:number }}
        token: ${{ secrets.TOKEN }}
    
