on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: "Build & Release edit"
jobs:
  build: 
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: 3.3.1
     - run: flutter pub get
     - run: flutter test
     - run: flutter build apk
    
