on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: "Build & Release edit"
jobs:
  build: 
    name: Build & Release
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: 3.19.0
     - run: flutter pub get
     - run: flutter test
     - run: |
         flutter build ios --no-codesign
         cd build/ios/iphoneos
         mkdir Payload
         cd Payload
         ln -s ../Runner.app
         cd ..
         zip -r app.ipa Payload
    #  - run: flutter build apk --release --split-per-abi
     - name: upload artifacts
       uses: ncipollo/release-action@v1
       with:
        artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}
    
